input:
  data_fn: data/R101_S15.fits
  randoms_fn: 
  format: xyz 
  rdz: [X, Y, Z]
  rdz_randoms: 
  mask: 
  mask_randoms:
  weights: 
  weights_randoms:

output:
  handle: R101_S15 
  seeds_fn: R101_S15_seeds

algorithm:
  selection_function: uniform
  box_size: 2000
  smoothing_radius: 20
  nseeds: 10000
  nquantiles: 5
  nthreads: 4

cosmology:
  omega_m: 0.307
