input:
  data_fn: data/mock_data.fits
  randoms_fn: 
  format: xyz 
  xyz: [X, Y, Z]
  rdz_randoms: 
  mask: 
  mask_randoms:
  weights: 
  weights_randoms:

output:
  handle: mock_data 
  seeds_fn: mock_data 

algorithm:
  selection_function: uniform
  box_size: 1500
  smoothing_radius: 20
  nseeds: 1000000
  nquantiles: 5
  nthreads: 4

cosmology:
  omega_m: 0.307
