input:
  dir: ./
  data_fn: data/mock_data.fits
  randoms_fn: 
  format: xyz 
  xyz: [X, Y, Z]
  rdz_randoms: 
  mask: 
  mask_randoms:
  weights: 
  weights_randoms:

output:
  dir: ./
  quantiles_fn: data/quantiles.npy
  density_fn: data/density_pdf.npy
  save_density: True
  seeds_fn: mock_data 

algorithm:
  selection_function: uniform
  box_size: 1500
  smooth_radius: 15
  smooth_type: tophat
  nseeds: 5000000
  auto_nseeds: False
  nquantiles: 5
  nthreads: 4

cosmology:
  omega_m: 0.307
